# Name: Oliver De Sa
# SciNet username: tmp_odesa
# Description:
#   Driver script for Assignment 7

source('C:/Users/Oliver/MSC1090/assignment7/A7.Utilities.R')

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 1){
  cat('Please input only 1 argument', '\n')
} else if (is.na(as.numeric(args))){
  cat('Please input a numeric argument', '\n')
} else {
  cat('There are', args, 'datapoints included in each batch of measured birds',
      '\n')

  # return the dataframe generated by ang.diff.CI
  CI.df <- ang.diff.CI(args, 1000, 2000)
  
  # return the plotted results of CI.df
  plot.CIs(CI.df)
}


