# Name: Oliver De Sa
# SciNet username: tmp_odesa
# Description:
#   Driver script for Assignment 7

source('C:/Users/Oliver/MSC1090/assignment7/A7.Utilities.R')

args <- commandArgs(trailingOnly = TRUE)

# add defensive

# return the dataframe generated by ang.diff.CI
CI.df <- ang.diff.CI(args, 1000, 2000)

# return the plotted results of CI.df
plot.CIs(CI.df)



